# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  buildConfiguration: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ env.buildConfiguration }} --no-restore
    - name: Test
      run: dotnet test --configuration ${{ env.buildConfiguration }} --no-build --verbosity normal
    - name: Publish dotnet app
      run: dotnet publish  --configuration ${{ env.buildConfiguration }} --output ${{ github.workspace }}/app
    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ github.workspace }}/app
        name: dotnet-app

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    environment: dev
    steps:
    - name: Download artifact
      with:
        name: dotnet-app
      uses: actions/download-artifact@v3
    - name: Deploy app
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  
    
